/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projet_dussart_cousseau;

import java.awt.Color;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.JButton;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


/**
 *
 * @author alice
 */
public class FenetrePrincipale extends javax.swing.JFrame {

    /**
     * Creates new form FenetrePrincipale
     */
    
    PlateauDeJeu Plateau;
    int NbCouleur = 4;
    int NbEssais = 10;
    int LongeurCombi = 4;
    ArrayList<Character> couleursDisponibles ;
    boolean JeuEncours =false;
    public FenetrePrincipale() {
        initComponents();
        JeuEncours =false;
    
     

 
 


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConfigJeux = new javax.swing.JPanel();
        ChoixNbCouleur = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ChoixNbEssais = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Choixlongeur = new javax.swing.JComboBox<>();
        BoutonJouer = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        PlateauJeux = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 51));
        setMinimumSize(new java.awt.Dimension(650, 781));
        setPreferredSize(new java.awt.Dimension(550, 680));
        setSize(new java.awt.Dimension(550, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ConfigJeux.setBackground(new java.awt.Color(0, 242, 242));
        ConfigJeux.setToolTipText("");

        ChoixNbCouleur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
        ChoixNbCouleur.setSelectedIndex(3);
        ChoixNbCouleur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChoixNbCouleurActionPerformed(evt);
            }
        });

        jLabel1.setText("Nb couleurs :");

        jLabel2.setText("Nb essais :");

        ChoixNbEssais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" }));
        ChoixNbEssais.setSelectedIndex(9);
        ChoixNbEssais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChoixNbEssais(evt);
            }
        });

        jLabel3.setText("Longeur: :");

        Choixlongeur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        Choixlongeur.setSelectedIndex(3);
        Choixlongeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChoixLongueur(evt);
            }
        });

        BoutonJouer.setText("JOUER");
        BoutonJouer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonJouerActionPerformed(evt);
            }
        });

        jLabel4.setText("Règles du jeu :");

        jLabel5.setText("1. Devinez la combinaison secrète de couleurs.");

        jLabel6.setText("2. Vous recevrez des indices ");

        jLabel7.setText("   - Nombre de pions bien placés (noirs).");

        jLabel8.setText("   - Nombre de pions corrects mais mal placés (blancs).");

        jLabel9.setText("3. Vous avez un nombre limité de tentatives.");

        jLabel11.setText("Paramètres :");

        javax.swing.GroupLayout ConfigJeuxLayout = new javax.swing.GroupLayout(ConfigJeux);
        ConfigJeux.setLayout(ConfigJeuxLayout);
        ConfigJeuxLayout.setHorizontalGroup(
            ConfigJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfigJeuxLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(ConfigJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ConfigJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ChoixNbEssais, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(ConfigJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ConfigJeuxLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ChoixNbCouleur, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11)))
                    .addGroup(ConfigJeuxLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(Choixlongeur, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BoutonJouer, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addGroup(ConfigJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(ConfigJeuxLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(ConfigJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))))
                .addGap(43, 43, 43))
        );
        ConfigJeuxLayout.setVerticalGroup(
            ConfigJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfigJeuxLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(ConfigJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConfigJeuxLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ConfigJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(ChoixNbCouleur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ConfigJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChoixNbEssais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ConfigJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Choixlongeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ConfigJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BoutonJouer, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(ConfigJeuxLayout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jLabel9))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(ConfigJeux, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 160));

        javax.swing.GroupLayout PlateauJeuxLayout = new javax.swing.GroupLayout(PlateauJeux);
        PlateauJeux.setLayout(PlateauJeuxLayout);
        PlateauJeuxLayout.setHorizontalGroup(
            PlateauJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        PlateauJeuxLayout.setVerticalGroup(
            PlateauJeuxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        getContentPane().add(PlateauJeux, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 150, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChoixNbCouleurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChoixNbCouleurActionPerformed
        // TODO add your handling code here:
        if (JeuEncours == true) return;
        this.NbCouleur = ChoixNbCouleur.getSelectedIndex()+1;
       
         
        
    }//GEN-LAST:event_ChoixNbCouleurActionPerformed

    private void BoutonJouerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonJouerActionPerformed
        // TODO add your handling code here:
        if (JeuEncours == true) return;
        
        this.NbCouleur = ChoixNbCouleur.getSelectedIndex()+1;
        this.NbEssais = ChoixNbEssais.getSelectedIndex()+1;
        this.LongeurCombi = Choixlongeur.getSelectedIndex()+1;
        
        JeuEncours =true;
        LancerPartie() ;
    }//GEN-LAST:event_BoutonJouerActionPerformed

    private void ChoixNbEssais(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChoixNbEssais
        // TODO add your handling code here:
        if (JeuEncours == true) return;
                
        this.NbEssais = ChoixNbEssais.getSelectedIndex()+1;
        
    }//GEN-LAST:event_ChoixNbEssais

    private void ChoixLongueur(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChoixLongueur
        // TODO add your handling code here:
        if (JeuEncours == true) return;
         this.LongeurCombi = Choixlongeur.getSelectedIndex()+1;
        
    }//GEN-LAST:event_ChoixLongueur

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetrePrincipale().setVisible(true);
            }
        });
    }
    
    private void AfficherPlateau(){
          
       
     
        
     

        PlateauJeux.removeAll();
        PlateauJeux.setLayout( new GridLayout(this.NbEssais+1, this.LongeurCombi*2+1));
        getContentPane().add(PlateauJeux, new
        org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, (LongeurCombi*2+1) * 30, (NbEssais+1) * 30));
        this.pack();
        this.revalidate();
        
        for (int i=0; i < this.NbEssais+1; i++) {
            final int ligne = i;
            for (int j=0; j < this.LongeurCombi*2+1; j++ ) {
                final int col = j;
                DessinePion bouton_cellule;
                if (j < this.LongeurCombi)
                    if (i == 0)
                        bouton_cellule = new DessinePion(Plateau, i,j, 4,30,30);
                    else
                       bouton_cellule = new DessinePion(Plateau,i,j, 1,30,30); // création d'un bouton}
                else if (j == this.LongeurCombi)
                   if (i == 0)
                        bouton_cellule = new DessinePion(Plateau, i,j,5,30,30);
                   else 
                       bouton_cellule = new DessinePion(Plateau, i,j,2,30,30);
                else 
                   if (i == 0)
                        bouton_cellule = new DessinePion(Plateau, i,j,5,30,30);
                    else
                       bouton_cellule = new DessinePion(Plateau, i,j,3,30,30);
                ActionListener ecouteurClick = new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                    clickposition(ligne,col);
                    repaint();
                    }

                };
                bouton_cellule.addActionListener(ecouteurClick);
                PlateauJeux.add(bouton_cellule); // ajout au Jpanel PanneauGrille
        
                PlateauJeux.revalidate();
                PlateauJeux.repaint();  
        
    }
      } 
}        
  
    
    private void LancerPartie() {
        //Liste des couleurs :
        this.couleursDisponibles = new ArrayList<>();
        if (NbCouleur>0) couleursDisponibles.add('R'); //Rouge
        if (NbCouleur>1) couleursDisponibles.add('G'); //Vert
        if (NbCouleur>2) couleursDisponibles.add('B'); //Bleu
        if (NbCouleur>3) couleursDisponibles.add('Y'); //Jaune
        if (NbCouleur>4) couleursDisponibles.add('P'); //Rose
        if (NbCouleur>5) couleursDisponibles.add('O'); //Orange
        if (NbCouleur>6) couleursDisponibles.add('W'); //Blanc
        
        Combinaison combinaisonSecrete = new Combinaison(LongeurCombi);
        combinaisonSecrete.genererAleatoire(LongeurCombi, this.couleursDisponibles);

        this.Plateau = new PlateauDeJeu( couleursDisponibles, combinaisonSecrete, NbEssais, LongeurCombi);
        AfficherPlateau();

    }

    public Character GetNextColor(Character couleur)
    {
        int pos = 0;
                
        for (int i = 0; i< couleursDisponibles.size();i++)
            if (couleur ==  couleursDisponibles.get(i))
            {
                pos = i;
                break;
            }
                
        if (pos < couleursDisponibles.size()-1)
                return couleursDisponibles.get(pos+1);
        else 
            return couleursDisponibles.get(0);
        
     
    }


      private void clickposition(int ligne,int col) {
        
        int size = Plateau.tentatives.size();
        Pion pion;
        Character coul;
        if (ligne == size+1 )
            if (col < LongeurCombi){
                pion= Plateau.combiEnCours.elements[col];
                coul = pion.getCouleur();
                pion.setCouleur(GetNextColor(coul));
            }
            else if (col == LongeurCombi)
                Plateau.proposerCombinaison(Plateau.combiEnCours);
             
  
        AfficherPlateau();
        
        if (Plateau.estVictoire() == true)
        {
            Plateau.affichereponse = true;
            JeuEncours = false;
            FenetreVictoire f = new FenetreVictoire() ;
            f.setDefaultCloseOperation(FenetreVictoire.DISPOSE_ON_CLOSE);
            f.setVisible(true) ;
        }
        
        if (Plateau.estDefaite() == true)
            {
                 Plateau.affichereponse = true;
                JeuEncours = false;
                FenetreDefaite f = new FenetreDefaite() ;
                 f.setDefaultCloseOperation(FenetreDefaite.DISPOSE_ON_CLOSE);
                f.setVisible(true) ;
            }
        
        AfficherPlateau();   
    
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonJouer;
    private javax.swing.JComboBox<String> ChoixNbCouleur;
    private javax.swing.JComboBox<String> ChoixNbEssais;
    private javax.swing.JComboBox<String> Choixlongeur;
    private javax.swing.JPanel ConfigJeux;
    private javax.swing.JPanel PlateauJeux;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}


